# Generated by Django 4.2.3 on 2023-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='creation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statistic/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='publication_feature',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак публикации'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='views_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
    ]
